spring:
  application:
    name: spring-batch-rule-poc-1

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/poc
    driver-class-name: org.postgresql.Driver
    username: xinhua
    password: 
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Spring Batch Configuration
  batch:
    job:
      enabled: false  # Disable auto job execution on startup
    jdbc:
      initialize-schema: always  # Initialize batch metadata tables
      table-prefix: BATCH_

# Logging Configuration
logging:
  level:
    root: INFO
    com.accenture.poc1: DEBUG
    org.springframework.batch: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans
  endpoint:
    health:
      show-details: always